name: Deploy all apps to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Set up Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - name: Install dependencies
        run: pnpm i

      - name: Build simon.duhem.fr
        run: pnpm --filter simon.duhem.fr build

      - name: Build ia-postrophe
        run: pnpm --filter ia-postrophe build

      - name: Build slides (HTML)
        uses: docker://marpteam/marp-cli:v4.2.3
        with:
          args: -I apps/slides/src -o apps/slides/dist
        env:
          MARP_USER: root:root

      - name: Build slides (PDF)
        uses: docker://marpteam/marp-cli:v4.2.3
        with:
          args: -I apps/slides/src -o apps/slides/dist --pdf --allow-local-files
        env:
          MARP_USER: root:root

      - name: Build slides (PPTX)
        uses: docker://marpteam/marp-cli:v4.2.3
        with:
          args: -I apps/slides/src -o apps/slides/dist --pptx --allow-local-files
        env:
          MARP_USER: root:root

      - name: Prepare public folder
        run: |
          mkdir -p public/ia-postrophe
          mkdir -p public/slides/assets
          cp -r apps/simon.duhem.fr/dist/* public/
          cp -r apps/ia-postrophe/dist/ia-postrophe/* public/ia-postrophe/
          cp -r apps/slides/src/assets/* public/slides/assets/
          cp -r apps/slides/dist/* public/slides/

      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
