name: Renovate Changesets
on:
  pull_request:
    branches: ['renovate/**']

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Generate changesets for Renovate
        run: pnpm changeset:renovate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changesets
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "chore: update changesets for Renovate" || echo "No changes to commit"
          git push
